import { db } from "@/db";
import { hosts, listings as listingsTable } from "@/db/schema";
import { enhanceListings, processListings } from "@/lib/listings-processor";
import type { Listing } from "@/types/listings";

export const listingSelect = {
  // Listings fields
  id: listingsTable.id,
  listing_url: listingsTable.listing_url,
  scrape_id: listingsTable.scrape_id,
  last_scraped: listingsTable.last_scraped,
  source: listingsTable.source,
  name: listingsTable.name,
  description: listingsTable.description,
  neighborhood_overview: listingsTable.neighborhood_overview,
  picture_url: listingsTable.picture_url,
  neighbourhood: listingsTable.neighbourhood,
  neighbourhood_cleansed: listingsTable.neighbourhood_cleansed,
  neighbourhood_group_cleansed: listingsTable.neighbourhood_group_cleansed,
  latitude: listingsTable.latitude,
  longitude: listingsTable.longitude,
  property_type: listingsTable.property_type,
  room_type: listingsTable.room_type,
  accommodates: listingsTable.accommodates,
  bathrooms: listingsTable.bathrooms,
  bathrooms_text: listingsTable.bathrooms_text,
  bedrooms: listingsTable.bedrooms,
  beds: listingsTable.beds,
  amenities: listingsTable.amenities,
  price: listingsTable.price,
  minimum_nights: listingsTable.minimum_nights,
  maximum_nights: listingsTable.maximum_nights,
  minimum_minimum_nights: listingsTable.minimum_minimum_nights,
  maximum_minimum_nights: listingsTable.maximum_minimum_nights,
  minimum_maximum_nights: listingsTable.minimum_maximum_nights,
  maximum_maximum_nights: listingsTable.maximum_maximum_nights,
  minimum_nights_avg_ntm: listingsTable.minimum_nights_avg_ntm,
  maximum_nights_avg_ntm: listingsTable.maximum_nights_avg_ntm,
  calendar_updated: listingsTable.calendar_updated,
  has_availability: listingsTable.has_availability,
  availability_30: listingsTable.availability_30,
  availability_60: listingsTable.availability_60,
  availability_90: listingsTable.availability_90,
  availability_365: listingsTable.availability_365,
  calendar_last_scraped: listingsTable.calendar_last_scraped,
  number_of_reviews: listingsTable.number_of_reviews,
  number_of_reviews_ltm: listingsTable.number_of_reviews_ltm,
  number_of_reviews_l30d: listingsTable.number_of_reviews_l30d,
  availability_eoy: listingsTable.availability_eoy,
  number_of_reviews_ly: listingsTable.number_of_reviews_ly,
  estimated_occupancy_l365d: listingsTable.estimated_occupancy_l365d,
  estimated_revenue_l365d: listingsTable.estimated_revenue_l365d,
  first_review: listingsTable.first_review,
  last_review: listingsTable.last_review,
  review_scores_rating: listingsTable.review_scores_rating,
  review_scores_accuracy: listingsTable.review_scores_accuracy,
  review_scores_cleanliness: listingsTable.review_scores_cleanliness,
  review_scores_checkin: listingsTable.review_scores_checkin,
  review_scores_communication: listingsTable.review_scores_communication,
  review_scores_location: listingsTable.review_scores_location,
  review_scores_value: listingsTable.review_scores_value,
  license: listingsTable.license,
  instant_bookable: listingsTable.instant_bookable,
  calculated_host_listings_count: listingsTable.calculated_host_listings_count,
  calculated_host_listings_count_entire_homes:
    listingsTable.calculated_host_listings_count_entire_homes,
  calculated_host_listings_count_private_rooms:
    listingsTable.calculated_host_listings_count_private_rooms,
  calculated_host_listings_count_shared_rooms:
    listingsTable.calculated_host_listings_count_shared_rooms,
  reviews_per_month: listingsTable.reviews_per_month,
  // Host fields
  host_id: hosts.id,
  host_url: hosts.url,
  host_name: hosts.name,
  host_since: hosts.since,
  host_location: hosts.location,
  host_about: hosts.about,
  host_response_time: hosts.response_time,
  host_response_rate: hosts.response_rate,
  host_acceptance_rate: hosts.acceptance_rate,
  host_is_superhost: hosts.is_superhost,
  host_thumbnail_url: hosts.thumbnail_url,
  host_picture_url: hosts.picture_url,
  host_neighbourhood: hosts.neighbourhood,
  host_listings_count: hosts.listings_count,
  host_total_listings_count: hosts.total_listings_count,
  host_verifications: hosts.verifications,
  host_has_profile_pic: hosts.has_profile_pic,
  host_identity_verified: hosts.identity_verified,
};

export function rowToListing(row: any): Listing {
  return {
    id: String(row.id),
    listing_url: row.listing_url || "",
    scrape_id: String(row.scrape_id || ""),
    last_scraped: row.last_scraped?.toString() || "",
    source: row.source || "",
    name: row.name || "",
    description: row.description || "",
    neighborhood_overview: row.neighborhood_overview || "",
    picture_url: row.picture_url || "",
    host_id: String(row.host_id || ""),
    host_url: row.host_url || "",
    host_name: row.host_name || "",
    host_since: row.host_since?.toString() || "",
    host_location: row.host_location || "",
    host_about: row.host_about || "",
    host_response_time: row.host_response_time || "",
    host_response_rate: row.host_response_rate || "",
    host_acceptance_rate: row.host_acceptance_rate || "",
    host_is_superhost: String(row.host_is_superhost || false),
    host_thumbnail_url: row.host_thumbnail_url || "",
    host_picture_url: row.host_picture_url || "",
    host_neighbourhood: row.host_neighbourhood || "",
    host_listings_count: String(row.host_listings_count || ""),
    host_total_listings_count: String(row.host_total_listings_count || ""),
    host_verifications: row.host_verifications || "",
    host_has_profile_pic: String(row.host_has_profile_pic || false),
    host_identity_verified: String(row.host_identity_verified || false),
    neighbourhood: row.neighbourhood || "",
    neighbourhood_cleansed: row.neighbourhood_cleansed || "",
    neighbourhood_group_cleansed: row.neighbourhood_group_cleansed || "",
    latitude: String(row.latitude || ""),
    longitude: String(row.longitude || ""),
    property_type: row.property_type || "",
    room_type: row.room_type || "",
    accommodates: String(row.accommodates || ""),
    bathrooms: String(row.bathrooms || ""),
    bathrooms_text: row.bathrooms_text || "",
    bedrooms: String(row.bedrooms || ""),
    beds: String(row.beds || ""),
    amenities: row.amenities || "",
    price: row.price || "",
    minimum_nights: String(row.minimum_nights || ""),
    maximum_nights: String(row.maximum_nights || ""),
    minimum_minimum_nights: String(row.minimum_minimum_nights || ""),
    maximum_minimum_nights: String(row.maximum_minimum_nights || ""),
    minimum_maximum_nights: String(row.minimum_maximum_nights || ""),
    maximum_maximum_nights: String(row.maximum_maximum_nights || ""),
    minimum_nights_avg_ntm: String(row.minimum_nights_avg_ntm || ""),
    maximum_nights_avg_ntm: String(row.maximum_nights_avg_ntm || ""),
    calendar_updated: row.calendar_updated || "",
    has_availability: String(row.has_availability || false),
    availability_30: String(row.availability_30 || ""),
    availability_60: String(row.availability_60 || ""),
    availability_90: String(row.availability_90 || ""),
    availability_365: String(row.availability_365 || ""),
    calendar_last_scraped: row.calendar_last_scraped?.toString() || "",
    number_of_reviews: String(row.number_of_reviews || ""),
    number_of_reviews_ltm: String(row.number_of_reviews_ltm || ""),
    number_of_reviews_l30d: String(row.number_of_reviews_l30d || ""),
    availability_eoy: String(row.availability_eoy || ""),
    number_of_reviews_ly: String(row.number_of_reviews_ly || ""),
    estimated_occupancy_l365d: String(row.estimated_occupancy_l365d || ""),
    estimated_revenue_l365d: String(row.estimated_revenue_l365d || ""),
    first_review: row.first_review?.toString() || "",
    last_review: row.last_review?.toString() || "",
    review_scores_rating: String(row.review_scores_rating || ""),
    review_scores_accuracy: String(row.review_scores_accuracy || ""),
    review_scores_cleanliness: String(row.review_scores_cleanliness || ""),
    review_scores_checkin: String(row.review_scores_checkin || ""),
    review_scores_communication: String(row.review_scores_communication || ""),
    review_scores_location: String(row.review_scores_location || ""),
    review_scores_value: String(row.review_scores_value || ""),
    license: row.license || "",
    instant_bookable: String(row.instant_bookable || false),
    calculated_host_listings_count: String(row.calculated_host_listings_count || ""),
    calculated_host_listings_count_entire_homes: String(
      row.calculated_host_listings_count_entire_homes || "",
    ),
    calculated_host_listings_count_private_rooms: String(
      row.calculated_host_listings_count_private_rooms || "",
    ),
    calculated_host_listings_count_shared_rooms: String(
      row.calculated_host_listings_count_shared_rooms || "",
    ),
    reviews_per_month: String(row.reviews_per_month || ""),
    potential_revenue: 0,
    risk_score: 0,
  };
}

export async function fetchListings(rawListings: any[]): Promise<Listing[]> {
  const listings = rawListings.map(rowToListing);
  const processedListings = processListings(listings);
  const enhancedListings = enhanceListings(processedListings);
  return enhancedListings;
}