import { describe, expect, it } from "vitest";
import {
  calculateRiskScore,
  enhanceListings,
  processListings,
} from "./listings-processor";
import type { Listing } from "@/types/listings";

describe("listings-processor", () => {
  const mockListings: Listing[] = [
    {
      id: "1",
      listing_url: "",
      scrape_id: "",
      last_scraped: "",
      source: "",
      name: "Test Listing 1",
      description: "",
      neighborhood_overview: "",
      picture_url: "",
      host_id: "1",
      host_url: "",
      host_name: "Host 1",
      host_since: "",
      host_location: "",
      host_about: "",
      host_response_time: "",
      host_response_rate: "",
      host_acceptance_rate: "",
      host_is_superhost: "",
      host_thumbnail_url: "",
      host_picture_url: "",
      host_neighbourhood: "",
      host_listings_count: "",
      host_total_listings_count: "",
      host_verifications: "",
      host_has_profile_pic: "",
      host_identity_verified: "",
      neighbourhood: "Midtown",
      neighbourhood_cleansed: "",
      neighbourhood_group_cleansed: "Manhattan",
      latitude: "40.7589",
      longitude: "-73.9851",
      property_type: "",
      room_type: "Entire home/apt",
      accommodates: "",
      bathrooms: "",
      bathrooms_text: "",
      bedrooms: "",
      beds: "",
      amenities: "",
      price: "100",
      minimum_nights: "1",
      maximum_nights: "",
      minimum_minimum_nights: "",
      maximum_minimum_nights: "",
      minimum_maximum_nights: "",
      maximum_maximum_nights: "",
      minimum_nights_avg_ntm: "",
      maximum_nights_avg_ntm: "",
      calendar_updated: "",
      has_availability: "",
      availability_30: "",
      availability_60: "",
      availability_90: "",
      availability_365: "200",
      calendar_last_scraped: "",
      number_of_reviews: "10",
      number_of_reviews_ltm: "5",
      number_of_reviews_l30d: "",
      availability_eoy: "",
      number_of_reviews_ly: "",
      estimated_occupancy_l365d: "",
      estimated_revenue_l365d: "",
      first_review: "",
      last_review: "2023-01-01",
      review_scores_rating: "",
      review_scores_accuracy: "",
      review_scores_cleanliness: "",
      review_scores_checkin: "",
      review_scores_communication: "",
      review_scores_location: "",
      review_scores_value: "",
      license: "",
      instant_bookable: "",
      calculated_host_listings_count: "1",
      calculated_host_listings_count_entire_homes: "",
      calculated_host_listings_count_private_rooms: "",
      calculated_host_listings_count_shared_rooms: "",
      reviews_per_month: "2.5",
      potential_revenue: 0,
      risk_score: 0,
    },
    {
      id: "2",
      listing_url: "",
      scrape_id: "",
      last_scraped: "",
      source: "",
      name: "Test Listing 2",
      description: "",
      neighborhood_overview: "",
      picture_url: "",
      host_id: "2",
      host_url: "",
      host_name: "Host 2",
      host_since: "",
      host_location: "",
      host_about: "",
      host_response_time: "",
      host_response_rate: "",
      host_acceptance_rate: "",
      host_is_superhost: "",
      host_thumbnail_url: "",
      host_picture_url: "",
      host_neighbourhood: "",
      host_listings_count: "",
      host_total_listings_count: "",
      host_verifications: "",
      host_has_profile_pic: "",
      host_identity_verified: "",
      neighbourhood: "Midtown",
      neighbourhood_cleansed: "",
      neighbourhood_group_cleansed: "Manhattan",
      latitude: "40.7589",
      longitude: "-73.9851",
      property_type: "",
      room_type: "Private room",
      accommodates: "",
      bathrooms: "",
      bathrooms_text: "",
      bedrooms: "",
      beds: "",
      amenities: "",
      price: "50",
      minimum_nights: "2",
      maximum_nights: "",
      minimum_minimum_nights: "",
      maximum_minimum_nights: "",
      minimum_maximum_nights: "",
      maximum_maximum_nights: "",
      minimum_nights_avg_ntm: "",
      maximum_nights_avg_ntm: "",
      calendar_updated: "",
      has_availability: "",
      availability_30: "",
      availability_60: "",
      availability_90: "",
      availability_365: "100",
      calendar_last_scraped: "",
      number_of_reviews: "5",
      number_of_reviews_ltm: "2",
      number_of_reviews_l30d: "",
      availability_eoy: "",
      number_of_reviews_ly: "",
      estimated_occupancy_l365d: "",
      estimated_revenue_l365d: "",
      first_review: "",
      last_review: "2023-01-01",
      review_scores_rating: "",
      review_scores_accuracy: "",
      review_scores_cleanliness: "",
      review_scores_checkin: "",
      review_scores_communication: "",
      review_scores_location: "",
      review_scores_value: "",
      license: "",
      instant_bookable: "",
      calculated_host_listings_count: "1",
      calculated_host_listings_count_entire_homes: "",
      calculated_host_listings_count_private_rooms: "",
      calculated_host_listings_count_shared_rooms: "",
      reviews_per_month: "1.0",
      potential_revenue: 0,
      risk_score: 0,
    },
    {
      id: "3",
      listing_url: "",
      scrape_id: "",
      last_scraped: "",
      source: "",
      name: "Invalid Price Listing",
      description: "",
      neighborhood_overview: "",
      picture_url: "",
      host_id: "3",
      host_url: "",
      host_name: "Host 3",
      host_since: "",
      host_location: "",
      host_about: "",
      host_response_time: "",
      host_response_rate: "",
      host_acceptance_rate: "",
      host_is_superhost: "",
      host_thumbnail_url: "",
      host_picture_url: "",
      host_neighbourhood: "",
      host_listings_count: "",
      host_total_listings_count: "",
      host_verifications: "",
      host_has_profile_pic: "",
      host_identity_verified: "",
      neighbourhood: "Williamsburg",
      neighbourhood_cleansed: "",
      neighbourhood_group_cleansed: "Brooklyn",
      latitude: "40.7081",
      longitude: "-73.9571",
      property_type: "",
      room_type: "Entire home/apt",
      accommodates: "",
      bathrooms: "",
      bathrooms_text: "",
      bedrooms: "",
      beds: "",
      amenities: "",
      price: "0",
      minimum_nights: "1",
      maximum_nights: "",
      minimum_minimum_nights: "",
      maximum_minimum_nights: "",
      minimum_maximum_nights: "",
      maximum_maximum_nights: "",
      minimum_nights_avg_ntm: "",
      maximum_nights_avg_ntm: "",
      calendar_updated: "",
      has_availability: "",
      availability_30: "",
      availability_60: "",
      availability_90: "",
      availability_365: "365",
      calendar_last_scraped: "",
      number_of_reviews: "0",
      number_of_reviews_ltm: "0",
      number_of_reviews_l30d: "",
      availability_eoy: "",
      number_of_reviews_ly: "",
      estimated_occupancy_l365d: "",
      estimated_revenue_l365d: "",
      first_review: "",
      last_review: "",
      review_scores_rating: "",
      review_scores_accuracy: "",
      review_scores_cleanliness: "",
      review_scores_checkin: "",
      review_scores_communication: "",
      review_scores_location: "",
      review_scores_value: "",
      license: "",
      instant_bookable: "",
      calculated_host_listings_count: "1",
      calculated_host_listings_count_entire_homes: "",
      calculated_host_listings_count_private_rooms: "",
      calculated_host_listings_count_shared_rooms: "",
      reviews_per_month: "",
      potential_revenue: 0,
      risk_score: 0,
    },
  ];

  describe("processListings", () => {
    it("should filter out invalid listings (price <= 0)", () => {
      const result = processListings(mockListings);
      expect(result).toHaveLength(2);
      expect(result.find((l) => l.id === "3")).toBeUndefined();
    });

    it("should process valid listings", () => {
      const result = processListings(mockListings);
      expect(result.every((l) => parseFloat(l.price) > 0)).toBe(true);
    });
  });

  describe("enhanceListings", () => {
    it("should calculate potential_revenue and risk_score", () => {
      const processed = processListings(mockListings);
      const result = enhanceListings(processed);

      expect(result[0].potential_revenue).toBe(100 * 200); // price * availability
      expect(result[0].risk_score).toBeGreaterThanOrEqual(0);
      expect(result[1].potential_revenue).toBe(50 * 100);
    });
  });

  describe("calculateRiskScore", () => {
    it("should calculate risk score for entire home", () => {
      const listing = mockListings[0];
      const score = calculateRiskScore(listing);
      expect(score).toBeGreaterThanOrEqual(0);
    });

    it("should calculate risk score for private room", () => {
      const listing = mockListings[1];
      const score = calculateRiskScore(listing);
      expect(score).toBeGreaterThan(0); // Should be higher than entire home
    });
  });
});
