CREATE TABLE "listings" (
	"id" integer PRIMARY KEY NOT NULL,
	"listing_url" text,
	"scrape_id" bigint,
	"last_scraped" date,
	"source" text,
	"name" text,
	"description" text,
	"neighborhood_overview" text,
	"picture_url" text,
	"host_id" bigint,
	"host_url" text,
	"host_name" text,
	"host_since" date,
	"host_location" text,
	"host_about" text,
	"host_response_time" text,
	"host_response_rate" text,
	"host_acceptance_rate" text,
	"host_is_superhost" boolean,
	"host_thumbnail_url" text,
	"host_picture_url" text,
	"host_neighbourhood" text,
	"host_listings_count" integer,
	"host_total_listings_count" integer,
	"host_verifications" text,
	"host_has_profile_pic" boolean,
	"host_identity_verified" boolean,
	"neighbourhood" text,
	"neighbourhood_cleansed" text,
	"neighbourhood_group_cleansed" text,
	"latitude" numeric(10, 8),
	"longitude" numeric(11, 8),
	"property_type" text,
	"room_type" text,
	"accommodates" integer,
	"bathrooms" numeric(3, 1),
	"bathrooms_text" text,
	"bedrooms" integer,
	"beds" integer,
	"amenities" text,
	"price" text,
	"minimum_nights" integer,
	"maximum_nights" integer,
	"minimum_minimum_nights" integer,
	"maximum_minimum_nights" integer,
	"minimum_maximum_nights" integer,
	"maximum_maximum_nights" integer,
	"minimum_nights_avg_ntm" numeric(15, 2),
	"maximum_nights_avg_ntm" numeric(15, 2),
	"calendar_updated" text,
	"has_availability" boolean,
	"availability_30" integer,
	"availability_60" integer,
	"availability_90" integer,
	"availability_365" integer,
	"calendar_last_scraped" date,
	"number_of_reviews" integer,
	"number_of_reviews_ltm" integer,
	"number_of_reviews_l30d" integer,
	"availability_eoy" integer,
	"number_of_reviews_ly" integer,
	"estimated_occupancy_l365d" numeric(5, 2),
	"estimated_revenue_l365d" numeric(15, 2),
	"first_review" date,
	"last_review" date,
	"review_scores_rating" numeric(3, 2),
	"review_scores_accuracy" numeric(3, 2),
	"review_scores_cleanliness" numeric(3, 2),
	"review_scores_checkin" numeric(3, 2),
	"review_scores_communication" numeric(3, 2),
	"review_scores_location" numeric(3, 2),
	"review_scores_value" numeric(3, 2),
	"license" text,
	"instant_bookable" boolean,
	"calculated_host_listings_count" integer,
	"calculated_host_listings_count_entire_homes" integer,
	"calculated_host_listings_count_private_rooms" integer,
	"calculated_host_listings_count_shared_rooms" integer,
	"reviews_per_month" numeric(4, 2)
);
