import { pgTable, integer, bigint, text, boolean, decimal, date } from 'drizzle-orm/pg-core';

export const listings = pgTable('listings', {
  id: bigint('id', { mode: 'number' }).primaryKey(),
  listing_url: text('listing_url'),
  scrape_id: bigint('scrape_id', { mode: 'number' }),
  last_scraped: date('last_scraped'),
  source: text('source'),
  name: text('name'),
  description: text('description'),
  neighborhood_overview: text('neighborhood_overview'),
  picture_url: text('picture_url'),
  host_id: bigint('host_id', { mode: 'number' }),
  host_url: text('host_url'),
  host_name: text('host_name'),
  host_since: date('host_since'),
  host_location: text('host_location'),
  host_about: text('host_about'),
  host_response_time: text('host_response_time'),
  host_response_rate: text('host_response_rate'),
  host_acceptance_rate: text('host_acceptance_rate'),
  host_is_superhost: boolean('host_is_superhost'),
  host_thumbnail_url: text('host_thumbnail_url'),
  host_picture_url: text('host_picture_url'),
  host_neighbourhood: text('host_neighbourhood'),
  host_listings_count: bigint('host_listings_count', { mode: 'number' }),
  host_total_listings_count: bigint('host_total_listings_count', { mode: 'number' }),
  host_verifications: text('host_verifications'),
  host_has_profile_pic: boolean('host_has_profile_pic'),
  host_identity_verified: boolean('host_identity_verified'),
  neighbourhood: text('neighbourhood'),
  neighbourhood_cleansed: text('neighbourhood_cleansed'),
  neighbourhood_group_cleansed: text('neighbourhood_group_cleansed'),
  latitude: decimal('latitude', { precision: 10, scale: 8 }),
  longitude: decimal('longitude', { precision: 11, scale: 8 }),
  property_type: text('property_type'),
  room_type: text('room_type'),
  accommodates: integer('accommodates'),
  bathrooms: decimal('bathrooms', { precision: 3, scale: 1 }),
  bathrooms_text: text('bathrooms_text'),
  bedrooms: integer('bedrooms'),
  beds: integer('beds'),
  amenities: text('amenities'),
  price: text('price'),
  minimum_nights: integer('minimum_nights'),
  maximum_nights: integer('maximum_nights'),
  minimum_minimum_nights: integer('minimum_minimum_nights'),
  maximum_minimum_nights: integer('maximum_minimum_nights'),
  minimum_maximum_nights: integer('minimum_maximum_nights'),
  maximum_maximum_nights: integer('maximum_maximum_nights'),
  minimum_nights_avg_ntm: decimal('minimum_nights_avg_ntm', { precision: 15, scale: 2 }),
  maximum_nights_avg_ntm: decimal('maximum_nights_avg_ntm', { precision: 15, scale: 2 }),
  calendar_updated: text('calendar_updated'),
  has_availability: boolean('has_availability'),
  availability_30: integer('availability_30'),
  availability_60: integer('availability_60'),
  availability_90: integer('availability_90'),
  availability_365: integer('availability_365'),
  calendar_last_scraped: date('calendar_last_scraped'),
  number_of_reviews: integer('number_of_reviews'),
  number_of_reviews_ltm: integer('number_of_reviews_ltm'),
  number_of_reviews_l30d: integer('number_of_reviews_l30d'),
  availability_eoy: integer('availability_eoy'),
  number_of_reviews_ly: integer('number_of_reviews_ly'),
  estimated_occupancy_l365d: decimal('estimated_occupancy_l365d', { precision: 5, scale: 2 }),
  estimated_revenue_l365d: decimal('estimated_revenue_l365d', { precision: 15, scale: 2 }),
  first_review: date('first_review'),
  last_review: date('last_review'),
  review_scores_rating: decimal('review_scores_rating', { precision: 3, scale: 2 }),
  review_scores_accuracy: decimal('review_scores_accuracy', { precision: 3, scale: 2 }),
  review_scores_cleanliness: decimal('review_scores_cleanliness', { precision: 3, scale: 2 }),
  review_scores_checkin: decimal('review_scores_checkin', { precision: 3, scale: 2 }),
  review_scores_communication: decimal('review_scores_communication', { precision: 3, scale: 2 }),
  review_scores_location: decimal('review_scores_location', { precision: 3, scale: 2 }),
  review_scores_value: decimal('review_scores_value', { precision: 3, scale: 2 }),
  license: text('license'),
  instant_bookable: boolean('instant_bookable'),
  calculated_host_listings_count: integer('calculated_host_listings_count'),
  calculated_host_listings_count_entire_homes: integer('calculated_host_listings_count_entire_homes'),
  calculated_host_listings_count_private_rooms: integer('calculated_host_listings_count_private_rooms'),
  calculated_host_listings_count_shared_rooms: integer('calculated_host_listings_count_shared_rooms'),
  reviews_per_month: decimal('reviews_per_month', { precision: 4, scale: 2 }),
});